# Generated by Django 2.2.4 on 2019-08-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, default='image_url', upload_to='images/')),
                ('image_name', models.CharField(default='title', max_length=30)),
                ('image_caption', models.TextField()),
                ('comments', models.ManyToManyField(to='insta.Comment')),
                ('likes', models.ManyToManyField(to='insta.Likes')),
            ],
        ),
    ]
