# Generated by Django 2.2.4 on 2019-08-31 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0010_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
